onEvent('block.registry', e => {
    e.create('vintage_black_wool').material('wool').hardness(0.8).displayName('Vintage Black Wool')
    e.create('vintage_blue_wool').material('wool').hardness(0.8).displayName('Vintage Blue Wool')
    e.create('vintage_brown_wool').material('wool').hardness(0.8).displayName('Vintage Brown Wool')
    e.create('vintage_cyan_wool').material('wool').hardness(0.8).displayName('Vintage Cyan Wool')
    e.create('vintage_gray_wool').material('wool').hardness(0.8).displayName('Vintage Gray Wool')
    e.create('vintage_green_wool').material('wool').hardness(0.8).displayName('Vintage Green Wool')
    e.create('vintage_light_blue_wool').material('wool').hardness(0.8).displayName('Vintage Light Blue Wool')
    e.create('vintage_light_gray_wool').material('wool').hardness(0.8).displayName('Vintage Light Gray Wool')
    e.create('vintage_lime_wool').material('wool').hardness(0.8).displayName('Vintage Lime Wool')
    e.create('vintage_magenta_wool').material('wool').hardness(0.8).displayName('Vintage Magenta Wool')
    e.create('vintage_orange_wool').material('wool').hardness(0.8).displayName('Vintage Orange Wool')
    e.create('vintage_pink_wool').material('wool').hardness(0.8).displayName('Vintage Pink Wool')
    e.create('vintage_purple_wool').material('wool').hardness(0.8).displayName('Vintage Purple Wool')
    e.create('vintage_red_wool').material('wool').hardness(0.8).displayName('Vintage Red Wool')
    e.create('vintage_white_wool').material('wool').hardness(0.8).displayName('Vintage White Wool')
    e.create('vintage_yellow_wool').material('wool').hardness(0.8).displayName('Vintage Yellow Wool')
})